Fix compile error: `result type of conditional expression is ambiguous`
```
7>RTMSDFTextureSettingsCache.h(47): Error C2445 : result type of conditional expression is ambiguous: types 'const TEnumAsByte<TextureAddress>' and 'TextureAddress' can be converted to multiple common types
7>RTMSDFTextureSettingsCache.h(47): Reference C2445 : could be 'const TEnumAsByte<TextureAddress>'
7>RTMSDFTextureSettingsCache.h(47): Reference C2445 : or       'TextureAddress'
```